name: Test Secret of PAT record

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  use_pat:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use PAT
        env:
          BOND: ${{ secrets.BOND }} # Replace with your secret name
        run: |
          echo "Using PAT..."
          # Example: Using the PAT to authenticate with the GitHub API
          curl -H "Authorization: Bearer $BOND" https://api.github.com/user
          echo "This is bond: $BOND"
